### PR TITLE
[#87] Add type enum to geometry proto for lines and arcs

### LINKED ISSUE #87: Add an enum-typed attribute to geometry message to identify lines and arcs
The current geometry message identifies lines and arcs by a string. The protocol is missing a concrete definition of each of the shapes. Teams have to look for certain names as implicitly defined in the source code to get dimensions of the penalty area.

I suggest to add an optional attribute to `SSL_FieldCicularArc` and `SSL_FieldLineSegment`:

```
enum SSL_FieldShapeType {
  CenterCircle = 0;
  TopTouchLine = 1;
  BottomTouchLine = 2;
  LeftGoalLine = 3;
  RightGoalLine = 4;
  HalfwayLine = 5;
  CenterLine = 6;
  LeftPenaltyStretch = 7;
  RightPenaltyStretch = 8;
  LeftFieldLeftPenaltyStrech = 9;
  LeftFieldRightPenaltyStrech = 10;
  RightFieldLeftPenaltyStrech = 11;
  RightFieldRightPenaltyStrech = 12;
}

message SSL_FieldLineSegment {
...
optional SSL_FieldShapeType = 5;
...
}

message SSL_FieldCicularArc {
...
optional SSL_FieldShapeType = 7;
...
}
```

### PR DESCRIPTION
**Pull request by g3force**
closes #87

### CODE REVIEW

**Comment by g3force** [comment]
I started this one last year. Time to finish it up.

**Comment by joydeep-b** [comment]
I went over this, and it seems fine, just want to confirm the use case - is the idea to specify what part of the field each line is supposed to represent?
@g3force

**Comment by joydeep-b** [comment]
Ah, missed the conversation in the Issue. Sounds good.

**Comment by joydeep-b** [comment]
@g3force Feel free to merge when ready.

**Comment by g3force** [comment]
yeah. Right now, all the lines and arcs have standardized names, but they are encoded as strings. To find the field dimensions, you have to expect lines with certain names.

I think, the reason why I still not merged this is, that I'd like to also have some parameters directly in the protobuf structure, like field length, etc, so that teams do not need extract them from the lines.

I'll have a look at it later.

**Comment by joydeep-b** [comment]
We can have a redundant `length` field for the lines, to make it easy.

**Comment by g3force** [comment]
I mixed things up. I thought there is no field length and width in the protobuf, but it is. The lines should be fine as is. I'll have a more detailed look later and get this merged.

**Comment by g3force** [comment]
I found, what I wanted to add: The penalty area dimensions where only implicitly encoded into the lines. I added dedicated fields next to the field dimensions, so teams do not have to extract the dimensions from the lines.

**Pull request merged**
