### PR TITLE
Optimize color thresholding by using SIMD instructions

### PR DESCRIPTION
**Pull request by g3force**

### CODE REVIEW

**Comment by joydeep-b** [comment]
Can you share the speedup numbers, @g3force ?
This should be hidden behind an SSE detection flag to ensure it is compiled if (and only if) the target supports SSE3. 

Potential solution:
https://stackoverflow.com/questions/28939652/how-to-detect-sse-sse2-avx-avx2-avx-512-avx-128-fma-kcvi-availability-at-compile

**Comment by g3force** [comment]
https://docs.google.com/spreadsheets/d/1NSrU4v9CXz7-20ZYo8ViBtGx1fmVF3BF-aC9ySRO4Ss/edit#gid=0

**Comment by g3force** [comment]
The numbers are from my laptop. I used the fromfile capture module to read raw images.
Speedup without threads is 36%, with 8 threads 10%

Btw, most of the code is from @andre-ryll

**Comment by g3force** [comment]
I use the `__AVX2__`  detection flag now.

**Comment by andre-ryll** [comment]
I tested this on the designated NUC with the real camera and with visualisation turned off this gets to max fps (73) easily. Around ~40% total CPU usage.

**Comment by g3force** [comment]
any further concerns? Otherwise, I'll merge it.

**Pull request merged**
